version: '3'

networks:
  network:
    ipam:
      driver: default
      config:
       - subnet: "172.16.100.0/24"


services:

  opensuse:
    build: ./build
    volumes:
      - ./data:/data
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    restart: unless-stopped
    tty: true
    hostname: opensuse
    mem_reservation: 256m
    mem_limit: 512m
    cpu_count: 1
    cpu_percent: 50
    privileged: true
    networks:
      network:
        ipv4_address: 172.16.100.10
